package com.blizzardprofiles.warcraft;

public enum AzeritePowersEnum {
    AZERITE_POWERS(13, "Azerite Empowered"),
    LONGSTRIDER(14, "Longstrider"),
    RESOUNDING_PROTECTION(15, "Resounding Protection"),
    BLOOD_SIPHON(18, "Blood Siphon"),
    WOUND_BINDER(19, "Woundbinder"),
    LIFE_SPEED(20, "Lifespeed"),
    ELEMENTAL_WHIRL(21, "Elemental Whirl"),
    HEED_MY_CALL(22, "Heed My Call"),
    OVERHELMING_POWER(30, "Overwhelming Power"),
    GUTRIPPER(31, "Gutripper"),
    IN_THE_RHYTHM(36, "In The Rhythm"),
    ON_MY_WAY(38, "On My Way"),
    SAVIOR(42, "Savior"),
    WINDS_OF_WAR(43, "Winds of War"),
    VAMPIRIC_SPEED(44, "Vampiric Speed"),
    SECRET_INFUSION(76, "Secret Infusion"),
    CHAMPION_OF_AZEROTH(82, "Champion of Azeroth"),
    IMPASSIVEVISAGE(83, "Impassive Visage"),
    BULWARK_OF_THE_MASSES(84, "Bulwark of the Masses"),
    GEM_HIDE(85, "Gemhide"),
    AZERITE_FORTIFICATION(86, "Azerite Fortification"),
    SELF_RELIANCE(87, "Self Reliance"),
    ARCANE_PUMMELING(88, "Arcane Pummeling"),
    AZERITE_VEINS(89, "Azerite Veins"),
    CRYSTALLINE_CARAPACE(98, "Crystalline Carapace"),
    ABLATIVE_SHIELDING(99, "Ablative Shielding"),
    STRENGTH_IN_NUMBERS(100, "Strength in Numbers"),
    SHIMMERING_HAVEN(101, "Shimmering Haven"),
    SYNERGISTIC_GROWTH(102, "Synergistic Growth"),
    CONCENTRATED_MENDING(103, "Concentrated Mending"),
    BRAZING_CHILL(104, "Bracing Chill"),
    EPHEMERAL_RECOVERY(105, "Ephemeral Recovery"),
    DEER_CUTS(106, "Deep Cuts"),
    SERRATED_JAWS(107, "Serrated Jaws"),
    ICY_CITADEL(108, "Icy Citadel"),
    MAGUS_OF_THE_DEAD(109, "Magus of the Dead"),
    WILDFIRE_CLUSTER(110, "Wildfire Cluster"),
    BLOOD_MIST(111, "Blood Mist"),
    LAYERED_MANE(112, "Layered Mane"),
    MOMENT_OF_REPOSE(113, "Moment of Repose"),
    PERMEATING_GLOW(114, "Permeating Glow"),
    SEARING_DIALOGUE(115, "Searing Dialogue"),
    BOILING_BREW(116, "Boiling Brew"),
    FURY_OF_XUEN(117, "Fury of Xuen"),
    DEAFENING_CRASH(118, "Deafening Crash"),
    UNBRIDLED_FEROCITY(119, "Unbridled Ferocity"),
    EARLY_HARVEST(120, "Early Harvest"),
    STRIKING_THE_ANVIL(121, "Striking the Anvil"),
    STREAKING_STARS(122, "Streaking Stars"),
    WARCKING_BRILLIANCE(123, "Wracking Brilliance"),
    REPLICATING_SHADOWS(124, "Replicating Shadows"),
    AVENGERS_MIGHT(125, "Avenger's Might"),
    REVOLIVING_BLADES(126, "Revolving Blades"),
    EQUIPOISE(127, "Equipoise"),
    FLAMES_OF_ALACRITY(128, "Flames of Alacrity"),
    DEADSHOT(129, "Deadshot"),
    SHADOWS_BITE(130, "Shadow's Bite"),
    CHAOS_SHARDS(131, "Chaos Shards"),
    PACKED_ICE(132, "Packed Ice"),
    BULWARK_OF_LIGHT(133, "Bulwark of Light"),
    REVEL_IN_PAIN(134, "Revel in Pain"),
    DOUBLE_DOSE(136, "Double Dose"),
    PRIMAL_PRIMER(137, "Primal Primer"),
    SOOTHING_WATERS(138, "Soothing Waters"),
    GLIMMER_OF_LIGHT(139, "Glimmer of Light"),
    BONE_SPIKE_GRAVEYARD(140, "Bone Spike Graveyard"),
    LATENT_CHILL(141, "Latent Chill"),
    HELCHAINS(142, "Helchains"),
    INSPIRING_BEACON(143, "Inspiring Beacon"),
    REJUVENATION_GRACE(144, "Rejuvenating Grace"),
    FORTIFYING_AURAS(145, "Fortifying Auras"),
    RIGHTEOUS_FLAMES(148, "Righteous Flames"),
    HEALING_HAMMER(149, "Healing Hammer"),
    SEARING_SHIELD(150, "Soaring Shield"),
    RELENTLESS_INQUISITOR(154, "Relentless Inquisitor"),
    RUINOUS_BOLT(156, "Ruinous Bolt"),
    REZANS_FURY(157, "Rezan's Fury"),
    FURIOUS_GAZE(159, "Furious Gaze"),
    INFERNAL_ARMOR(160, "Infernal Armor"),
    HAZE_OF_RAGE(161, "Haze of Rage"),
    SURGING_SHOTS(162, "Surging Shots"),
    LATENT_POISON(163, "Latent Poison"),
    WEAL_AND_WOE(164, "Weal and Woe"),
    BLESSED_SANCTUARY(165, "Blessed Sanctuary"),
    THOUGHT_HARVESTER(166, "Thought Harvester"),
    BRAIN_STORM(167, "Brain Storm"),
    WILDFIRE(168, "Wildfire"),
    UNTAMED_FEROCITY(169, "Untamed Ferocity"),
    FLASH_FREEZE(170, "Flash Freeze"),
    MASTERFUL_INSTINCTS(171, "Masterful Instincts"),
    GROVE_TENDING(172, "Grove Tending"),
    POWER_OF_THE_MOON(173, "Power of the Moon"),
    GATHERING_STORM(174, "Gathering Storm"),
    NIGHTS_VENGEANCE(175, "Night's Vengeance"),
    COLD_STEEL_HOT_BLOOD(176, "Cold Steel, Hot Blood"),
    BLOODSPORT(177, "Bloodsport"),
    LAVA_SHOT(178, "Lava Shock"),
    STRENGTH_OF_EARTH(179, "Strength of Earth"),
    KEEP_YOUR_WITS_ABOUT_YOU(180, "Keep Your Wits About You"),
    TWIST_THE_KNIFE(181, "Twist the Knife"),
    INEVITABLE_DEMISE(183, "Inevitable Demise"),
    SUNRISE_TECHNIQUE(184, "Sunrise Technique"),
    OVERFLOWING_MISTS(185, "Overflowing Mists"),
    STAGERING_STRIKES(186, "Staggering Strikes"),
    EXPURGATION(187, "Expurgation"),
    MOMENT_OF_COMPASSION(188, "Moment of Compassion"),
    RIGHTEOUS_CONVICTION(189, "Righteous Conviction"),
    UMBRAL_BLAZE(190, "Umbral Blaze"),
    TURN_OF_THE_TIDE(191, "Turn of the Tide"),
    METICULOUS_SCHEMING(192, "Meticulous Scheming"),
    BLIGHTBORNE_INFUSION(193, "Blightborne Infusion"),
    FLITHY_TRANSFUSION(194, "Filthy Transfusion"),
    SECRETS_OF_THE_DEER(195, "Secrets of the Deep"),
    SWIRLING_SANDS(196, "Swirling Sands"),
    MARROWBLOOD(197, "Marrowblood"),
    FROSTWHELPS_INDIGNATION(198, "Frostwhelp's Indignation"),
    FESTERMIGHT(199, "Festermight"),
    ARCANIC_PULSAR(200, "Arcanic Pulsar"),
    RUNIC_BARRIER(201, "Runic Barrier"),
    SOULMONGER(202, "Soulmonger"),
    SHELLSHOCK(203, "Shellshock"),
    SANCTUM(204, "Sanctum"),
    ELDRITCH_WARDING(205, "Eldritch Warding"),
    STALWART_PROTECTOR(206, "Stalwart Protector"),
    SERENE_SPIRIT(207, "Serene Spirit"),
    LIFEBLOOD(208, "Lifeblood"),
    JUNGLE_FURY(209, "Jungle Fury"),
    AUTUMN_LEAVES(210, "Autumn Leaves"),
    DANCE_OF_DEATH(211, "Dance of Death"),
    UNERRING_VISION(212, "Unerring Vision"),
    VENOMS_FANGS(213, "Venomous Fangs"),
    ARCANE_PRESSURE(214, "Arcane Pressure"),
    BLASTER_MASTER(215, "Blaster Master"),
    FOOTPAD(217, "Footpad"),
    STRENGTH_OF_SPIRIT(218, "Strength of Spirit"),
    REAWAKENING(219, "Reawakening"),
    CHAOTIC_TRANSFORMATION(220, "Chaotic Transformation"),
    RIGID_CARAPACE(221, "Rigid Carapace"),
    ECHO_OF_THE_ELEMENTALS(222, "Echo of the Elementals"),
    LIGHTNING_CONDUIT(223, "Lightning Conduit"),
    SWELLING_STREAM(224, "Swelling Stream"),
    GLACIAL_ASSAULT(225, "Glacial Assault"),
    TEST_OF_MIGHT(226, "Test of Might"),
    DEPTH_OF_THE_SHADOWS(227, "Depth of the Shadows"),
    PRAYERFUL_LITANY(228, "Prayerful Litany"),
    PULVERIZING_BLOWS(229, "Pulverizing Blows"),
    CASCADING_CALAMITY(230, "Cascading Calamity"),
    EXPLOSIVE_POTENTIAL(231, "Explosive Potential"),
    FLASHPOINT(232, "Flashpoint"),
    DIVINE_REVELATIONS(233, "Divine Revelations"),
    INNER_LIGHT(234, "Inner Light"),
    INDOMITABLE_JUSTICE(235, "Indomitable Justice"),
    WHISPERS_OF_THE_DAMNED(236, "Whispers of the Damned"),
    BASTION_OF_MIGHT(237, "Bastion of Might"),
    FIT_TO_BURST(238, "Fit to Burst"),
    SNAKE_EYES(239, "Snake Eyes"),
    BLADE_IN_THE_SHADOWS(240, "Blade In The Shadows"),
    TWISTED_CLAWS(241, "Twisted Claws"),
    ECHOING_HOWL(242, "Echoing Howl"),
    BLOODY_RUNEBLADE(243, "Bloody Runeblade"),
    HARROWING_DECAY(244, "Harrowing Decay"),
    SEETHING_POWER(245, "Seething Power"),
    HOUR_OF_REAPING(246, "Hour of Reaping"),
    IRON_JAWS(247, "Iron Jaws"),
    MISTY_PEAKS(248, "Misty Peaks"),
    NOTHING_PERSONAL(249, "Nothing Personal"),
    DAWNING_SUN(250, "Dawning Sun"),
    BURST_OF_SAVAGERY(251, "Burst of Savagery"),
    KILLER_FROST(346, "Killer Frost"),
    FROZEN_TEMPEST(347, "Frozen Tempest"),
    ETERNAL_RUNE_WEAPON(348, "Eternal Rune Weapon"),
    BONES_OF_THE_DAMNED(349, "Bones of the Damned"),
    CANKEROUS_WOUNDS(350, "Cankerous Wounds"),
    LAST_SURPRISE(351, "Last Surprise"),
    THIRSTING_BLADES(352, "Thirsting Blades"),
    EYES_OF_RAGE(353, "Eyes of Rage"),
    CYCLE_OF_BINDING(354, "Cycle of Binding"),
    ESSENCE_SEVER(355, "Essence Sever"),
    HIGH_NOON(356, "High Noon"),
    LUNAR_SHRAPNEL(357, "Lunar Shrapnel"),
    GUSHING_LACERATIONS(358, "Gushing Lacerations"),
    WILD_FLESHRENDING(359, "Wild Fleshrending"),
    GORY_REGENERATION(360, "Gory Regeneration"),
    GUARDIANS_WRATH(361, "Guardian's Wrath"),
    RAMPANT_GROWTH(362, "Rampant Growth"),
    WAKING_DREAM(363, "Waking Dream"),
    LIVELY_SPIRIT(364, "Lively Spirit"),
    DIRE_CONSEQUENCES(365, "Dire Consequences"),
    PRIMAL_INSTINCTS(366, "Primal Instincts"),
    FEEDING_FRENZY(367, "Feeding Frenzy"),
    STEADY_AIM(368, "Steady Aim"),
    RAPID_RELOAD(369, "Rapid Reload"),
    FOCUSED_FIRE(370, "Focused Fire"),
    BLUR_OF_TALONS(371, "Blur of Talons"),
    WILDERNESS_SURVIVAL(372, "Wilderness Survival"),
    PRIMEVAL_INTUITION(373, "Primeval Intuition"),
    GALVANIZING_SPARK(374, "Galvanizing Spark"),
    EXPLOSIVE_ECHO(375, "Explosive Echo"),
    TRAILING_EMBERS(376, "Trailing Embers"),
    DUPLICATIVE_INCINERATION(377, "Duplicative Incineration"),
    FIREMIND(378, "Firemind"),
    TUNNEL_OF_ICE(379, "Tunnel of Ice"),
    WHITEOUT(380, "Whiteout"),
    FRIGID_GRASP(381, "Frigid Grasp"),
    STRAIGHT_NO_CHASER(382, "Straight, No Chaser"),
    TRAINING_OF_NIUZAO(383, "Training of Niuzao"),
    ELUSIVE_FOOTWORK(384, "Elusive Footwork"),
    BURST_OF_LIFE(385, "Burst of Life"),
    FONT_OF_LIFE(386, "Font of Life"),
    UPLIFTED_SPIRITS(387, "Uplifted Spirits"),
    GLORY_OF_THE_DAWN(388, "Glory of the Dawn"),
    OPEN_PALM_STRIKES(389, "Open Palm Strikes"),
    PRESSURE_POINT(390, "Pressure Point"),
    DANCE_OF_CHIJI(391, "Dance of Chi-Ji"),
    GRACE_OF_THE_JUSTICAR(393, "Grace of the Justicar"),
    BREAKING_DAWN(394, "Breaking Dawn"),
    INSPIRING_VANGUARD(395, "Inspiring Vanguard"),
    LIGHTS_DECREE(396, "Light's Decree"),
    SUDDEN_REVELATION(397, "Sudden Revelation"),
    CONTEMPTUOUS_HOMILY(398, "Contemptuous Homily"),
    ENDURING_LUMINESCENCE(399, "Enduring Luminescence"),
    EVERLASTING_LIGHT(400, "Everlasting Light"),
    WORD_OF_MENDING(401, "Word of Mending"),
    PROMISE_OF_DELIVERANCE(402, "Promise of Deliverance"),
    SPITEFUL_APPARITIONS(403, "Spiteful Apparitions"),
    DEATH_THROES(404, "Death Throes"),
    CHORUS_OF_INSANITY(405, "Chorus of Insanity"),
    SCENT_OF_BLOOD(406, "Scent of Blood"),
    ECHOING_BLADES(407, "Echoing Blades"),
    SHROUDED_SUFFOCATION(408, "Shrouded Suffocation"),
    PARADISE_LOST(410, "Paradise Lost"),
    ACE_UP_YOUR_SLEEVE(411, "Ace Up Your Sleeve"),
    THE_FIRST_DANCE(413, "The First Dance"),
    INEVITABILITY(414, "Inevitability"),
    NATURAL_HARMONY(416, "Natural Harmony"),
    TECTONIC_THUNDER(417, "Tectonic Thunder"),
    ROILING_STORM(420, "Roiling Storm"),
    SURGING_TIDES(422, "Surging Tides"),
    SPOUTING_SPIRITS(423, "Spouting Spirits"),
    SUDDEN_ONSET(425, "Sudden Onset"),
    DREADFUL_CALLING(426, "Dreadful Calling"),
    DEMONIC_METEOR(428, "Demonic Meteor"),
    BALEFUL_INVOCATION(429, "Baleful Invocation"),
    ROLLING_HAVOC(431, "Rolling Havoc"),
    CHAOTIC_INFERNO(432, "Chaotic Inferno"),
    SEISMIC_WAVE(433, "Seismic Wave"),
    CRUSHING_ASSAULT(434, "Crushing Assault"),
    LORD_OF_WAR(435, "Lord of War"),
    SIMMERING_RAGE(437, "Simmering Rage"),
    RECKLESS_FLURRY(438, "Reckless Flurry"),
    CALLOUS_REPRISAL(440, "Callous Reprisal"),
    IRON_FORTRESS(441, "Iron Fortress"),
    PANDEMIC_INVOCATION(442, "Pandemic Invocation"),
    CRASHING_CHAOS(444, "Crashing Chaos"),
    PERFORATE(445, "Perforate"),
    BRIGANDS_BLITZ(446, "Brigand's Blitz"),
    ANCESTRAL_RESONANCE(447, "Ancestral Resonance"),
    SYNAPSE_SHOCK(448, "Synapse Shock"),
    OVERFLOWING_SHORES(449, "Overflowing Shores"),
    BRACE_FOR_IMPACT(450, "Brace for Impact"),
    INFINITE_FURY(451, "Infinite Fury"),
    RADIANT_INCANDESCENCE(452, "Radiant Incandescence"),
    EMPYREAN_POWER(453, "Empyrean Power"),
    JUDICIOUS_DEFENSE(454, "Judicious Defense"),
    IGNEOUS_POTENTIAL(457, "Igneous Potential"),
    SUPREME_COMMANDER(458, "Supreme Commander"),
    UNSTABLE_FLAMES(459, "Unstable Flames"),
    BURSTING_FLARE(460, "Bursting Flare"),
    EARTHLINK(461, "Earthlink"),
    AZERITE_GLOBULES(462, "Azerite Globules"),
    BLESSED_PORTENTS(463, "Blessed Portents"),
    MARCH_OF_THE_DAMNED(465, "March of the Damned"),
    BURNING_SOUL(466, "Burning Soul"),
    URSOCS_ENDURANCE(467, "Ursoc's Endurance"),
    CAUTERIZING_BLINK(468, "Cauterizing Blink"),
    DUCK_AND_COVER(469, "Duck and Cover"),
    SWEEP_THE_LEG(470, "Sweep the Leg"),
    GALLANT_STEED(471, "Gallant Steed"),
    TWIST_MAGIC(472, "Twist Magic"),
    SHROUDED_MANTLE(473, "Shrouded Mantle"),
    PACK_SPIRIT(474, "Pack Spirit"),
    DESPERATE_POWER(475, "Desperate Power"),
    MOMENT_OF_GLORY(476, "Moment of Glory"),
    BURY_THE_HATCHET(477, "Bury the Hatchet"),
    TIDAL_SURGE(478, "Tidal Surge"),
    DAGGER_IN_THE_BACK(479, "Dagger in the Back"),
    BLOOD_RITE(480, "Blood Rite"),
    INCITE_THE_PACK(481, "Incite the Pack"),
    THUNDEROUS_BLAST(482, "Thunderous Blast"),
    ARCHIVE_OF_THE_TITANS(483, "Archive of the Titans"),
    LASER_MATRIX(485, "Laser Matrix"),
    GLORY_IN_BATTLE(486, "Glory in Battle"),
    RETALIATORY_FURY(487, "Retaliatory Fury"),
    BATTLEFIELD_FOCUS(488, "Battlefield Focus"),
    SYLVANAS_RESOLVE(489, "Sylvanas' Resolve"),
    COMBINED_MIGHT(490, "Combined Might"),
    COLLECTIVE_WILL(491, "Collective Will"),
    LIBERATORS_MIGHT(492, "Liberator's Might"),
    LAST_GIFT(493, "Last Gift"),
    BATTLEFIELD_PRECISION(494, "Battlefield Precision"),
    ANDUINS_DEDICATION(495, "Anduin's Dedication"),
    STRONGER_TOGETHER(496, "Stronger Together"),
    STAND_AS_ONE(497, "Stand As One"),
    BARRAGE_OF_MANY_BOMBS(498, "Barrage Of Many Bombs"),
    RICOCHETING_INFLATABLE_PYROSAW(499, "Ricocheting Inflatable Pyrosaw"),
    SYNAPTIC_SPARK_CAPACITOR(500, "Synaptic Spark Capacitor"),
    RELATIONAL_NORMALIZATION_GIZMO(501, "Relational Normalization Gizmo"),
    PERSONAL_ABSORBOTRON(502, "Personal Absorb-o-Tron"),
    AUTOSELFCAUTERIZER(503, "Auto-Self-Cauterizer"),
    UNSTABLE_CATALYST(504, "Unstable Catalyst"),
    TRADEWINDS(505, "Tradewinds"),
    REPLICATING_SHADOWS2(506, "Replicating Shadows"),
    EMPYREAN_POWER2(507, "Empyrean Power"),
    LIGHTS_DECREE2(508, "Light's Decree"),
    NOTHING_PERSONAL2(509, "Nothing Personal"),
    HELCHAINS2(511, "Helchains"),
    TECTONIC_THUNDER2(512, "Tectonic Thunder"),
    STRAIGHT_NO_CHASER2(513, "Straight, No Chaser"),
    EQUIPOISE2(514, "Equipoise"),
    BALEFUL_INVOCATION2(515, "Baleful Invocation"),
    DANCE_OF_CHIJI2(516, "Dance of Chi-Ji"),
    FURY_OF_XUEN2(517, "Fury of Xuen"),
    DIRE_CONSEQUENCES2(518, "Dire Consequences"),
    FROSTWHELPS_INDIGNATION2(519, "Frostwhelp's Indignation"),
    BASTION_OF_MIGHT2(520, "Bastion of Might"),
    SHADOW_OF_ELUNE(521, "Shadow of Elune"),
    ANCIENTS_BULWARK(522, "Ancients' Bulwark"),
    APOTHECARYS_CONCOCTIONS(523, "Apothecary's Concoctions"),
    ECHOING_BLADES2(524, "Echoing Blades"),
    CHAOS_SHARDS2(525, "Chaos Shards"),
    ENDLESS_HUNGER(526, "Endless Hunger"),
    RIGHTEOUS_CONVICTION2(527, "Righteous Conviction"),
    SURGING_SHOTS2(528, "Surging Shots"),
    ARCANIC_PULSAR2(529, "Arcanic Pulsar"),
    THUNDERAANS_FURY(530, "Thunderaan's Fury"),
    TERROR_OF_THE_MIND(531, "Terror of the Mind"),
    EARLY_HARVEST2(532, "Early Harvest"),
    GLIMMER_OF_LIGHT2(533, "Glimmer of Light"),
    PROMISE_OF_DELIVERANCE2(534, "Promise of Deliverance"),
    SUDDEN_REVELATION2(535, "Sudden Revelation"),
    SECRET_INFUSION2(536, "Secret Infusion"),
    DEATH_DENIED(537, "Death Denied"),
    EMPYREAL_WARD(538, "Empyreal Ward"),
    ANCIENT_ANKH_TALISMAN(539, "Ancient Ankh Talisman"),
    SWITCH_HITTER(540, "Switch Hitter"),
    FIGHT_OR_FLIGHT(541, "Fight or Flight"),
    NATURES_SALVE(543, "Nature's Salve"),
    UNBRIDLED_FEROCITY2(544, "Unbridled Ferocity"),
    COLD_STEEL_HOT_BLOOD2(545, "Cold Steel, Hot Blood"),
    QUICK_THINKING(546, "Quick Thinking"),
    FLASH_FREEZE2(547, "Flash Freeze"),
    LYING_IN_WAIT(548, "Lying In Wait"),
    COLD_HEARTED(549, "Cold Hearted"),
    STRIKING_THE_ANVIL2(550, "Striking the Anvil"),
    PRIMEVAL_INTUITION2(551, "Primeval Intuition"),
    MAGUS_OF_THE_DEAD2(552, "Magus of the Dead"),
    INTIMIDATING_PRESENCE(554, "Intimidating Presence"),
    CHAOTIC_TRANSFORMATION2(555, "Chaotic Transformation"),
    WILDFIRE2(556, "Wildfire"),
    BLOODY_RUNEBLADE2(557, "Bloody Runeblade"),
    HOUR_OF_REAPING2(558, "Hour of Reaping"),
    BONDED_SOULS(560, "Bonded Souls"),
    SEDUCTIVE_POWER(561, "Seductive Power"),
    TREACHEROUS_COVENANT(562, "Treacherous Covenant"),
    THRIVE_IN_CHAOS(564, "Thrive in Chaos"),
    EXIT_STRATEGY(566, "Exit Strategy");

    private int id;
    private String name;

    AzeritePowersEnum(int id, String name) {
        this.id = id;
        this.name = name;
    }

    @Override
    public String toString() {
        return this.name;
    }

    public int getAzeritePowerAsInt() {
        return id;
    }

    public static AzeritePowersEnum convertIntToString(int fromId) {
        for (AzeritePowersEnum power : AzeritePowersEnum.values()) {
            if (power.getAzeritePowerAsInt() == fromId) {
                return power;
            }
        }
        return null;
    }
}
