package com.BlizzardArmory.warcraft.reputations.characterreputations

enum class RepByExpansion(expansion: String, name: String, faction: String) {
    RAJANI("Battle for Azeroth", "Rajani", ""),
    ULDUM_ACCORD("Battle for Azeroth", "Uldum Accord", ""),
    WAVEBLADE_ANKOAN("Battle for Azeroth", "Waveblade Ankoan", ""),
    SEVENTH_LEGION("Battle for Azeroth", "7th Legion", ""),
    STORMS_WAKE("Battle for Azeroth", "Storm's Wake", ""),
    ORDER_OF_EMBERS("Battle for Azeroth", "Order of Embers", ""),
    PROUDMOORE_ADMIRALTY("Battle for Azeroth", "Proudmoore Admiralty", ""),
    THE_UNSHACKLED("Battle for Azeroth", "The Unshackled", ""),
    THE_HONORBOUND("Battle for Azeroth", "The honourbound", ""),
    ZANDALARI_EMPIRE("Battle for Azeroth", "Zandalari Empire", ""),
    TALANJIS_EXPEDITION("Battle for Azeroth", "Talanji's Expedition", ""),
    VOLDUNAI("Battle for Azeroth", "Voludnai", ""),
    RUSTBOLT_RESISTANCE("Battle for Azeroth", "Rustbolt Resistance", ""),
    TORTOLLAN_SEEKERS("Battle for Azeroth", "Tortollan Seekers", ""),
    CHAMPIONS_OF_AZEROTH("Battle for Azeroth", "Champions of Azeroth", ""),
    ARMIES_OF_LEGIONFALL("Legion", "Armies of Legionfall", ""),
    CHROMIE("Legion", "Chromie", ""),
    ARMY_OF_THE_LIGHT("Legion", "Army of the Light", ""),
    ARGUSSIAN_REACH("Legion", "Argussian Reach", ""),
    COURT_OF_FARONDIS("Legion", "Court of Farondis", ""),
    DREAMWEAVERS("Legion", "Dreamweavers", ""),
    HIGHMOUNTAIN_TRIBE("Legion", "Highmountain Tribe", ""),
    TALONS_VENGEANCE("Legion", "Talon's Vengeance", ""),
    THE_NIGHTFALLEN("Legion", "The Nightfallen", ""),
    THE_WARDENS("Legion", "The Wardens", ""),
    VALARJAR("Legion", "Valarjar", ""),
    CONJURER_MARGOSS("Legion", "Conjurer Margoss", ""),
    WRYNNS_VANGUARD("Warlords of Draenor", "Wrynn's Vanguard", ""),
    VOLJINS_SPEAR("Warlords of Draenor", "Vol'jin's Spear", ""),
    HAND_OF_THE_PROPHET("Warlords of Draenor", "Hand of the Prophet", ""),
    VOLJINS_HEADHUNTERS("Warlords of Draenor", "Vol'jin's Headhunters", ""),
    ORDER_OF_THE_AWAKENED("Warlords of Draenor", "Order of the Awakened", ""),
    THE_SABERSTALKERS("Warlords of Draenor", "The Saberstalkers", ""),
    ARAKKOA_OUTCASTS("Warlords of Draenor", "Arakkoa Outcasts", ""),
    COUNCIL_OF_EXARCHS("Warlords of Draenor", "Council of Exarchs", ""),
    FROSTWOLF_ORCS("Warlords of Draenor", "Frostwolf Orcs", ""),
    LAUGHING_SKULL_ORCS("Warlords of Draenor", "Laughing Skull Orcs", ""),
    SHATARI_DEFENSE("Warlords of Draenor", "Sha'tari Defense", ""),
    DELVAR_IRONFIST("Warlords of Draenor", "Delvar Ironfist", "Barracks Bodyguards"),
    TALONPRIEST_ISHAAL("Warlords of Draenor", "Talonpriest Ishaal", "Barracks Bodyguards"),
    TORMMOK("Warlords of Draenor", "Tormmok", "Barracks Bodyguards"),
    STEAMWHEEDLE_PRESERVATION_SOCIETY("Warlords of Draenor", "Steamwheedle Preservation Society", ""),
    THE_AUGUST_CELESTIALS("Mists of Pandaria", "The August Celestials", ""),
    THE_ANGLERS("Mists of Pandaria", "The Anglers", "The Anglers"),
    NAT_PAGLE("Mists of Pandaria", "Nat Pagle", "The Anglers"),
    THE_BLACK_PRINCE("Mists of Pandaria", "The Black Prince", ""),
    GOLDEN_LOTUS("Mists of Pandaria", "Golden Lotus", ""),
    KIRIN_TOR_OFFENSIVE("Mists of Pandaria", "kirin Tor Offensive", ""),
    SUNREAVER_ONSLAUGHT("Mists of Pandaria", "Sunreaver Onslaught", ""),
    THE_KLAXXI("Mists of Pandaria", "The Klaxxi", ""),
    THE_LOREWALKERS("Mists of Pandaria", "The Lorewalkers", ""),
    OPERATION_SHIELDWALL("Mists of Pandaria", "Operation: Shieldwall", ""),
    DOMINANCE_OFFENSIVE("Mists of Pandaria", "Dominance Offensive", ""),
    ORDER_OF_THE_CLOUD_SERPENT("Mists of Pandaria", "Order of the Cloud Serpent", ""),
    PEARLFIN_JINYU("Mists of Pandaria", "Pearlfin Jinyu", ""),
    FOREST_HOZEN("Mists of Pandaria", "Forest Hozen", ""),
    EMPEROR_SHAOHAO("Mists of Pandaria", "Emperor Shaohao", ""),
    SHADO_PAN("Mists of Pandaria", "Shado-Pan", ""),
    SHADO_PAN_ASSAULT("Mists of Pandaria", "Shado-Pan Assault", ""),
    THE_TILLERS("Mists of Pandaria", "The Tillers", "The Tillers"),
    OLD_HILLPAW("Mists of Pandaria", "Old Hillpaw", "The Tillers"),
    ELLA("Mists of Pandaria", "Ella", "The Tillers"),
    FISH_FELLREED("Mists of Pandaria", "Fish Fellreed", "The Tillers"),
    FARMER_FUNG("Mists of Pandaria", "Farmer Fung", "The Tillers"),
    GINA_MUDCLAW("Mists of Pandaria", "Gina Mudclaw", "The Tillers"),
    SHO("Mists of Pandaria", "Sho", "The Tillers"),
    CHEE_CHEE("Mists of Pandaria", "Chee Chee", "The Tillers"),
    HAOHAN_MUDCLAW("Mists of Pandaria", "Haohan Mudclaw", "The Tillers"),
    JOGU_THE_DRUNK("Mists of Pandaria", "Jogu the Drunk", "The Tillers"),
    TINA_MUDCLAW("Mists of Pandaria", "Tina Mudclaw", "The Tillers"),
    AVENGERS_OF_HYJAL("Cataclysm", "Avengers of Hyjal", ""),
    BARADINS_WARDENS("Cataclysm", "Baradin's Wardens", ""),
    HELLSCREAMS_REACH("Cataclysm", "Hellscream's Reach", ""),
    DRAGONMAW_CLAN("Cataclysm", "Dragonmaw Clan", ""),
    WILDHAMMER_CLAN("Cataclysm", "Wildhammer Clan", ""),
    GUARDIANS_OF_HYJAL("Cataclysm", "Guardians of Hyjal", ""),
    RAMKAHEN("Cataclysm", "Ramkahen", ""),
    THE_EARTHEN_RING("Cataclysm", "The Earthen Ring", ""),
    THERAZANE("Cataclysm", "Therazane", ""),
    ALLIANCE_VANGUARD("Wrath of the Lich King", "Alliance Vanguard", "Alliance Vanguard"),
    ARGENT_CRUSADE("Wrath of the Lich King", "Argent Crusade", ""),
    HORDE_EXPEDITION("Wrath of the Lich King", "Horde Expedition", "Horde Expedition"),
    KIRIN_TOR("Wrath of the Lich King", "Kirin Tor", ""),
    KNIGHTS_OF_THE_EBON_BLADE("Wrath of the Lich King", "Knights of the Ebon Blade", ""),
    THE_ASHEN_VERDICT("Wrath of the Lich King", "The Ashen Verdict", ""),
    THE_KALUAK("Wrath of the Lich King", "The Kalu'ak", ""),
    THE_SONS_OF_HODIR("Wrath of the Lich King", "The Sons of Hodir", ""),
    THE_WYRMREST_ACCORD("Wrath of the Lich King", "The Wyrmrest Accord", ""),
    EXPLORERS_LEAGUE("Wrath of the Lich King", "Explorer's League", "Alliance Vanguard"),
    THE_FROSTBORN("Wrath of the Lich King", "The Frostborn", "Alliance Vanguard"),
    THE_SILVER_COVENANT("Wrath of the Lich King", "The Silver Covenant", "Alliance Vanguard"),
    VALIANCE_EXPEDITION("Wrath of the Lich King", "Valiance Expedition", "Alliance Vanguard"),
    THE_HAND_OF_VENGEANCE("Wrath of the Lich King", "The Hand of Vengeance", "Horde Expedition"),
    THE_SUNREAVERS("Wrath of the Lich King", "The Sunreavers", "Horde Expedition"),
    THE_TAUNKA("Wrath of the Lich King", "The Taunka", "Horde Expedition"),
    WARSONG_OFFENSIVE("Wrath of the Lich King", "Warsong Offensive", "Horde Expedition"),
    FRENZYHEART_TRIBE("Wrath of the Lich King", "Frenzyheart Tribe", "Scholozar Basin"),
    THE_ORACLES("Wrath of the Lich King", "The Oracles", "Scholozar Basin"),
    ASHTONGUE_DEATHSWORN("Burning Crusade", "Ashtongue Deathsworn", ""),
    CENARION_EXPEDITION("Burning Crusade", "Cenarion Expedition", ""),
    HONOR_HOLD("Burning Crusade", "Honor Hold", ""),
    THRALLMAR("Burning Crusade", "Thrallmar", ""),
    KEEPERS_OF_TIME("Burning Crusade", "Keepers of Time", ""),
    KURENAI("Burning Crusade", "Kurenai", ""),
    THE_MAGHAR("Burning Crusade", "The Mag'har", ""),
    NETHERWING("Burning Crusade", "Netherwing", ""),
    OGRILA("Burning Crusade", "Ogri'la", ""),
    SPOREGGAR("Burning Crusade", "Sporeggar", ""),
    THE_CONSORTIUM("Burning Crusade", "The Consortium", ""),
    THE_SCALE_OF_THE_SANDS("Burning Crusade", "The Scale of the Sands", ""),
    THE_VIOLET_EYE("Burning Crusade", "The Violet Eye", ""),
    TRANQUILLIEN("Burning Crusade", "Tranquillien", ""),
    LOWER_CITY("Burning Crusade", "Lower City", "Shattrath City"),
    SHATARI_SKYGUARD("Burning Crusade", "Sha'tari Skyguard", "Shattrath City"),
    SHATTERED_SUN_OFFENSIVE("Burning Crusade", "Shattered Sun Offensive", "Shattrath City"),
    THE_ALDOR("Burning Crusade", "The Aldor", "Shattrath City"),
    THE_SCRYERS("Burning Crusade", "The Scryers", "Shattrath City"),
    THE_SHATAR("Burning Crusade", "The Sha'tar", "Shattrath City"),
    ARGENT_DAWN("Classic", "Argent Dawn", ""),
    BLOODSAIL_BUCCANEERS("Classic", "Bloodsail Buccaneers", ""),
    BROOD_OF_NOZDORMU("Classic", "Brood of Nozdormu", ""),
    CENARION_CIRCLE("Classic", "Cenarion Circle", ""),
    DARKMOON_FAIRE("Classic", "Darkmoon Faire", ""),
    HYDRAXIAN_WATERLORDS("Classic", "Hydraxian Waterlords", ""),
    RAVENHOLDT("Classic", "Ravenholdt", ""),
    SYNDICATE("Classic", "Syndicate", ""),
    THORIUM_BROTHERHOOD("Classic", "Thorium Brotherhood", ""),
    TIMBERMAW_HOLD("Classic", "Timbermaw Hold", ""),
    WINTERSABER_TRAINERS("Classic", "Wintersaber Trainers", ""),
    GELKIS_CLAN_CENTAUR("Classic", "Gelkis Clan Centaur", ""),
    MAGRAM_CLAN_CENTAUR("Classic", "Magram Clan Centaur", ""),
    GUILD("Classic", "Guild", ""),
    SHENDRALAR("Classic", "Shen'dralar", ""),
    ZANDALAR_TRIBE("Classic", "Zandalar Tribe", ""),
    DARNASSUS("Classic", "Darnassus", "Alliance"),
    EXODAR("Classic", "Exodar", "Alliance"),
    GILNEAS("Classic", "Gilneas", "Alliance"),
    GNOMEREGAN("Classic", "Gnomeregan", "Alliance"),
    IRONFORGE("Classic", "Ironforge", "Alliance"),
    STORMWIND("Classic", "Stormwind", "Alliance"),
    TUSHUI_PANDAREN("Classic", "Tushui Pandaren", "Alliance"),
    BILGEWATER_CARTEL("Classic", "Bilgewater Cartel", "Horde"),
    DARKSPEAR_TROLLS("Classic", "Darkspear Trolls", "Horde"),
    ORGRIMMAR("Classic", "Orgrimmar", "Horde"),
    SILVERMOON_CITY("Classic", "Silvermoon City", "Horde"),
    THUNDER_BLUFF("Classic", "Thunder Bluff", "Horde"),
    UNDERCITY("Classic", "Undercity", "Horde"),
    HUOJIN_PANDAREN("Classic", "Huojin Pandaren", "Horde"),
    SILVERWING_SENTINELS("Classic", "Silverwing Sentinels", "Forces"),
    STORMPIKE_GUARD("Classic", "Stormpike Guard", "Forces"),
    THE_LEAGUE_OF_ARATHOR("Classic", "The League of Arathor", "Forces"),
    FROSTWOLF_CLAN("Classic", "Frostwolf Clan", "Forces"),
    THE_DEFILERS("Classic", "The Defilers", "Forces"),
    BRAWLGAR_ARENA_S1("Classic", "Brawl'gar Arena (Season 1)", "Forces"),
    BRAWLGAR_ARENA_S2("Classic", "Brawl'gar Arena (Season 2)", "Forces"),
    BRAWLGAR_ARENA_S3("Classic", "Brawl'gar Arena (Season 3)", "Forces"),
    BRAWLGAR_ARENA_S4("Classic", "Brawl'gar Arena (Season 4)", "Forces"),
    WARSONG_OUTRIDERS("Classic", "Warsong Outriders", "Forces"),
    RATCHET("Classic", "Ratcher", "Steamwheedle Cartel"),
    BOOTY_BAY("Classic", "Booty Bay", "Steamwheedle Cartel"),
    EVERLOOK("Classic", "Everlook", "Steamwheedle Cartel"),
    GADGETZAN("Classic", "Gadgetzan", "Steamwheedle Cartel");

    public var xpac: String = expansion
    public var repName: String = name
    public var factionName: String = faction

    companion object {
        fun getFaction(value: String): String? = values().find { it.repName == value }?.factionName
    }
}