package com.BlizzardArmory.util

enum class FragmentTag {
    WOWFAVORITES, D3FAVORITES, OWFAVORITES, D3NAV, D3FRAGMENT, D3LEADERBOARD, WOWRAIDLEADERBOARD, WOWMPLUSLEADERBOARD,
    WOWPVPLEADERBOARD, WOWGUILDNAVFRAGMENT, NAVFRAGMENT, WOWFRAGMENT, SC2FRAGMENT, OVERWATCHFRAGMENT, NEWSPAGEFRAGMENT,
    SETTINGSFRAGMENT, SC2LEADERBOARD, HELPFRAGMENT, LIBSFRAGMENT
}