package com.BlizzardArmory.model.warcraft.reputations.characterreputations

enum class RepByExpansion(expansion: String, name: String, faction: String, id: Int) {
    BARONESS_VASHJ("Shadowlands", "Baroness Vashj", "The Ember Court", 2446),
    LADY_MOONBERRY("Shadowlands", "Lady Moonberry", "The Ember Court", 2447),
    MIKANIKOS("Shadowlands", "Mikanikos", "The Ember Court", 2448),
    THE_COUNTESS("Shadowlands", "The Countess", "The Ember Court", 2449),
    ALEXANDROS_MORGRAINE("Shadowlands", "Alexandros Mograine", "The Ember Court", 2450),
    HUNT_CAPTAIN_KORAYN("Shadowlands", "Hunt-Captain Korayn", "The Ember Court", 2451),
    POLEMARCH_ADRESTES("Shadowlands", "Polemarch Adrestes", "The Ember Court", 2452),
    RENDLE_AND_CUDGELFACE("Shadowlands", "Rendle and Cudgelface", "The Ember Court", 2453),
    CHOOFA("Shadowlands", "Choofa", "The Ember Court", 2454),
    CRYPTKEEPER_KASSIR("Shadowlands", "Cryptkeeper Kassir", "The Ember Court", 2455),
    DROMAN_ALIOTHE("Shadowlands", "Droman Aliothe", "The Ember Court", 2456),
    GRANDMASTER_VOLE("Shadowlands", "Grandmaster Vole", "The Ember Court", 2457),
    KLEIA_AND_PELAGOS("Shadowlands", "Kleia and Pelagos", "The Ember Court", 2458),
    SIKA("Shadowlands", "Sika", "The Ember Court", 2459),
    STONEHEAD("Shadowlands", "Stonehead", "The Ember Court", 2460),
    PLAGUE_DEVISER_MARILETH("Shadowlands", "Plague Deviser Marileth", "The Ember Court", 2461),
    STITCHMASTERS("Shadowlands", "Stitchmasters", "", 2462),
    THE_EMBER_COURT("Shadowlands", "The Ember Court", "", 2445),
    VE_NARI("Shadowlands", "Ve'nari", "sl base", 2432),
    THE_WILD_HUNT("Shadowlands", "The Wild Hunt", "sl base", 2465),
    THE_UNDYING_ARMY("Shadowlands", "The Undying Army", "sl base", 2410),
    THE_ASCENDED("Shadowlands", "The Ascended", "sl base", 2407),
    THE_AVOWED("Shadowlands", "The Avowed", "sl base", 2439),
    COURT_OF_HARVESTERS("Shadowlands", "Court of Harvesters", "sl base", 2413),
    RAJANI("Battle for Azeroth", "Rajani", "", 2415),
    HONEYBACK_HIVE("Battle for Azeroth", "Honeyback Hive", "", 2395),
    ULDUM_ACCORD("Battle for Azeroth", "Uldum Accord", "", 2417),
    WAVEBLADE_ANKOAN("Battle for Azeroth", "Waveblade Ankoan", "", 2400),
    SEVENTH_LEGION("Battle for Azeroth", "7th Legion", "", 2159),
    STORMS_WAKE("Battle for Azeroth", "Storm's Wake", "", 2162),
    ORDER_OF_EMBERS("Battle for Azeroth", "Order of Embers", "", 2161),
    PROUDMOORE_ADMIRALTY("Battle for Azeroth", "Proudmoore Admiralty", "", 2160),
    THE_UNSHACKLED("Battle for Azeroth", "The Unshackled", "", 2373),
    THE_HONORBOUND("Battle for Azeroth", "The Honorbound", "", 2157),
    ZANDALARI_EMPIRE("Battle for Azeroth", "Zandalari Empire", "", 2103),
    TALANJIS_EXPEDITION("Battle for Azeroth", "Talanji's Expedition", "", 2156),
    VOLDUNAI("Battle for Azeroth", "Voldunai", "", 2158),
    RUSTBOLT_RESISTANCE("Battle for Azeroth", "Rustbolt Resistance", "", 2391),
    TORTOLLAN_SEEKERS("Battle for Azeroth", "Tortollan Seekers", "", 2163),
    CHAMPIONS_OF_AZEROTH("Battle for Azeroth", "Champions of Azeroth", "", 2164),
    ARMIES_OF_LEGIONFALL("Legion", "Armies of Legionfall", "", 2045),
    CHROMIE("Legion", "Chromie", "", 2135),
    ARMY_OF_THE_LIGHT("Legion", "Army of the Light", "", 2165),
    ARGUSSIAN_REACH("Legion", "Argussian Reach", "", 2170),
    COURT_OF_FARONDIS("Legion", "Court of Farondis", "", 1900),
    DREAMWEAVERS("Legion", "Dreamweavers", "", 1883),
    HIGHMOUNTAIN_TRIBE("Legion", "Highmountain Tribe", "", 1828),
    TALONS_VENGEANCE("Legion", "Talon's Vengeance", "", 2018),
    THE_NIGHTFALLEN("Legion", "The Nightfallen", "", 1859),
    THE_WARDENS("Legion", "The Wardens", "", 1894),
    VALARJAR("Legion", "Valarjar", "", 1948),
    CONJURER_MARGOSS("Legion", "Conjurer Margoss", "", 1975),
    WRYNNS_VANGUARD("Warlords of Draenor", "Wrynn's Vanguard", "", 1682),
    VOLJINS_SPEAR("Classic", "Vol'jin's Spear", "Forces", 1681),
    HAND_OF_THE_PROPHET("Warlords of Draenor", "Hand of the Prophet", "", 1847),
    VOLJINS_HEADHUNTERS("Warlords of Draenor", "Vol'jin's Headhunters", "", 1848),
    ORDER_OF_THE_AWAKENED("Warlords of Draenor", "Order of the Awakened", "", 1849),
    THE_SABERSTALKERS("Warlords of Draenor", "The Saberstalkers", "", 1850),
    ARAKKOA_OUTCASTS("Warlords of Draenor", "Arakkoa Outcasts", "", 1515),
    COUNCIL_OF_EXARCHS("Warlords of Draenor", "Council of Exarchs", "", 1731),
    FROSTWOLF_ORCS("Warlords of Draenor", "Frostwolf Orcs", "", 1445),
    LAUGHING_SKULL_ORCS("Warlords of Draenor", "Laughing Skull Orcs", "", 1708),
    SHATARI_DEFENSE("Warlords of Draenor", "Sha'tari Defense", "", 1710),
    DELVAR_IRONFIST("Warlords of Draenor", "Delvar Ironfist", "Barracks Bodyguards", 1733),
    TALONPRIEST_ISHAAL("Warlords of Draenor", "Talonpriest Ishaal", "Barracks Bodyguards", 1737),
    TORMMOK("Warlords of Draenor", "Tormmok", "Barracks Bodyguards", 1736),
    STEAMWHEEDLE_PRESERVATION_SOCIETY("Warlords of Draenor", "Steamwheedle Preservation Society", "", 1711),
    BIZMO_BRAWLPUB_SEASON_1("Classic", "Bizmo's Brawlpub (Season 1)", "bizmo", 1419),
    BIZMO_BRAWLPUB_SEASON_2("Classic", "Bizmo's Brawlpub (Season 1)", "bizmo", 1691),
    BIZMO_BRAWLPUB_SEASON_3("Classic", "Bizmo's Brawlpub (Season 1)", "bizmo", 2011),
    THE_AUGUST_CELESTIALS("Mists of Pandaria", "The August Celestials", "", 1341),
    THE_ANGLERS("Mists of Pandaria", "The Anglers", "The Anglers", 1302),
    NAT_PAGLE("Mists of Pandaria", "Nat Pagle", "The Anglers", 1358),
    THE_BLACK_PRINCE("Mists of Pandaria", "The Black Prince", "", 1359),
    GOLDEN_LOTUS("Mists of Pandaria", "Golden Lotus", "", 1269),
    KIRIN_TOR_OFFENSIVE("Mists of Pandaria", "kirin Tor Offensive", "", 1387),
    SUNREAVER_ONSLAUGHT("Mists of Pandaria", "Sunreaver Onslaught", "", 1388),
    THE_KLAXXI("Mists of Pandaria", "The Klaxxi", "", 1337),
    THE_LOREWALKERS("Mists of Pandaria", "The Lorewalkers", "", 1345),
    OPERATION_SHIELDWALL("Mists of Pandaria", "Operation: Shieldwall", "", 1376),
    DOMINANCE_OFFENSIVE("Mists of Pandaria", "Dominance Offensive", "", 1375),
    ORDER_OF_THE_CLOUD_SERPENT("Mists of Pandaria", "Order of the Cloud Serpent", "", 1271),
    PEARLFIN_JINYU("Mists of Pandaria", "Pearlfin Jinyu", "", 1242),
    FOREST_HOZEN("Mists of Pandaria", "Forest Hozen", "", 1228),
    EMPEROR_SHAOHAO("Mists of Pandaria", "Emperor Shaohao", "", 1492),
    SHADO_PAN("Mists of Pandaria", "Shado-Pan", "", 1270),
    SHADO_PAN_ASSAULT("Mists of Pandaria", "Shado-Pan Assault", "", 1435),
    THE_TILLERS("Mists of Pandaria", "The Tillers", "The Tillers", 1272),
    OLD_HILLPAW("Mists of Pandaria", "Old Hillpaw", "The Tillers", 1276),
    ELLA("Mists of Pandaria", "Ella", "The Tillers", 1275),
    FISH_FELLREED("Mists of Pandaria", "Fish Fellreed", "The Tillers", 1282),
    FARMER_FUNG("Mists of Pandaria", "Farmer Fung", "The Tillers", 1283),
    GINA_MUDCLAW("Mists of Pandaria", "Gina Mudclaw", "The Tillers", 1281),
    SHO("Mists of Pandaria", "Sho", "The Tillers", 1278),
    CHEE_CHEE("Mists of Pandaria", "Chee Chee", "The Tillers", 1277),
    HAOHAN_MUDCLAW("Mists of Pandaria", "Haohan Mudclaw", "The Tillers", 1279),
    JOGU_THE_DRUNK("Mists of Pandaria", "Jogu the Drunk", "The Tillers", 1273),
    TINA_MUDCLAW("Mists of Pandaria", "Tina Mudclaw", "The Tillers", 1280),
    SHANG_XI_ACADEMY("Mists of Pandaria", "Shang Xi's Academy", "", 1216),
    DARKSPEAR_REBELLION("Mists of Pandaria", "Darkspear Rebellion", "", 1440),
    AVENGERS_OF_HYJAL("Cataclysm", "Avengers of Hyjal", "", 1204),
    BARADINS_WARDENS("Cataclysm", "Baradin's Wardens", "", 1177),
    HELLSCREAMS_REACH("Cataclysm", "Hellscream's Reach", "", 1178),
    DRAGONMAW_CLAN("Cataclysm", "Dragonmaw Clan", "", 1172),
    WILDHAMMER_CLAN("Cataclysm", "Wildhammer Clan", "", 1174),
    GUARDIANS_OF_HYJAL("Cataclysm", "Guardians of Hyjal", "", 1158),
    RAMKAHEN("Cataclysm", "Ramkahen", "", 1173),
    THE_EARTHEN_RING("Cataclysm", "The Earthen Ring", "", 1135),
    THERAZANE("Cataclysm", "Therazane", "", 1171),
    ALLIANCE_VANGUARD("Wrath of the Lich King", "Alliance Vanguard", "Alliance Vanguard", 1037),
    ARGENT_CRUSADE("Wrath of the Lich King", "Argent Crusade", "", 1106),
    HORDE_EXPEDITION("Wrath of the Lich King", "Horde Expedition", "Horde Expedition", 1052),
    KIRIN_TOR("Wrath of the Lich King", "Kirin Tor", "", 1090),
    KNIGHTS_OF_THE_EBON_BLADE("Wrath of the Lich King", "Knights of the Ebon Blade", "", 1098),
    THE_ASHEN_VERDICT("Wrath of the Lich King", "The Ashen Verdict", "", 1156),
    THE_KALUAK("Wrath of the Lich King", "The Kalu'ak", "", 1073),
    THE_SONS_OF_HODIR("Wrath of the Lich King", "The Sons of Hodir", "", 1119),
    THE_WYRMREST_ACCORD("Wrath of the Lich King", "The Wyrmrest Accord", "", 1091),
    EXPLORERS_LEAGUE("Wrath of the Lich King", "Explorer's League", "Alliance Vanguard", 1068),
    THE_FROSTBORN("Wrath of the Lich King", "The Frostborn", "Alliance Vanguard", 1126),
    THE_SILVER_COVENANT("Wrath of the Lich King", "The Silver Covenant", "Alliance Vanguard", 1094),
    VALIANCE_EXPEDITION("Wrath of the Lich King", "Valiance Expedition", "Alliance Vanguard", 1050),
    THE_HAND_OF_VENGEANCE("Wrath of the Lich King", "The Hand of Vengeance", "Horde Expedition", 1067),
    THE_SUNREAVERS("Wrath of the Lich King", "The Sunreavers", "Horde Expedition", 1124),
    THE_TAUNKA("Wrath of the Lich King", "The Taunka", "Horde Expedition", 1064),
    WARSONG_OFFENSIVE("Wrath of the Lich King", "Warsong Offensive", "Horde Expedition", 1085),
    FRENZYHEART_TRIBE("Wrath of the Lich King", "Frenzyheart Tribe", "Scholozar Basin", 1104),
    THE_ORACLES("Wrath of the Lich King", "The Oracles", "Scholozar Basin", 1105),
    ASHTONGUE_DEATHSWORN("Burning Crusade", "Ashtongue Deathsworn", "", 1012),
    CENARION_EXPEDITION("Burning Crusade", "Cenarion Expedition", "", 942),
    HONOR_HOLD("Burning Crusade", "Honor Hold", "", 946),
    THRALLMAR("Burning Crusade", "Thrallmar", "", 947),
    KEEPERS_OF_TIME("Burning Crusade", "Keepers of Time", "", 989),
    KURENAI("Burning Crusade", "Kurenai", "", 978),
    THE_MAGHAR("Burning Crusade", "The Mag'har", "", 941),
    NETHERWING("Burning Crusade", "Netherwing", "", 1015),
    OGRILA("Burning Crusade", "Ogri'la", "", 1038),
    SPOREGGAR("Burning Crusade", "Sporeggar", "", 970),
    THE_CONSORTIUM("Burning Crusade", "The Consortium", "", 933),
    THE_SCALE_OF_THE_SANDS("Burning Crusade", "The Scale of the Sands", "", 990),
    THE_VIOLET_EYE("Burning Crusade", "The Violet Eye", "", 967),
    TRANQUILLIEN("Burning Crusade", "Tranquillien", "", 922),
    LOWER_CITY("Burning Crusade", "Lower City", "Shattrath City", 1011),
    SHATARI_SKYGUARD("Burning Crusade", "Sha'tari Skyguard", "Shattrath City", 1031),
    SHATTERED_SUN_OFFENSIVE("Burning Crusade", "Shattered Sun Offensive", "Shattrath City", 1077),
    THE_ALDOR("Burning Crusade", "The Aldor", "Shattrath City", 932),
    THE_SCRYERS("Burning Crusade", "The Scryers", "Shattrath City", 934),
    THE_SHATAR("Burning Crusade", "The Sha'tar", "Shattrath City", 935),
    ARGENT_DAWN("Classic", "Argent Dawn", "", 529),
    BLOODSAIL_BUCCANEERS("Classic", "Bloodsail Buccaneers", "", 87),
    BROOD_OF_NOZDORMU("Classic", "Brood of Nozdormu", "", 910),
    CENARION_CIRCLE("Classic", "Cenarion Circle", "", 609),
    DARKMOON_FAIRE("Classic", "Darkmoon Faire", "", 909),
    HYDRAXIAN_WATERLORDS("Classic", "Hydraxian Waterlords", "", 749),
    RAVENHOLDT("Classic", "Ravenholdt", "", 349),
    SYNDICATE("Classic", "Syndicate", "", 70),
    THORIUM_BROTHERHOOD("Classic", "Thorium Brotherhood", "", 59),
    TIMBERMAW_HOLD("Classic", "Timbermaw Hold", "", 576),
    WINTERSABER_TRAINERS("Classic", "Wintersaber Trainers", "", 589),
    GELKIS_CLAN_CENTAUR("Classic", "Gelkis Clan Centaur", "", 92),
    MAGRAM_CLAN_CENTAUR("Classic", "Magram Clan Centaur", "", 93),
    GUILD("Classic", "Guild", "", 1168),
    GUILD2("Classic", "Guild", "", 1169),
    SHENDRALAR("Classic", "Shen'dralar", "", 809),
    ZANDALAR_TRIBE("Classic", "Zandalar Tribe", "", 270),
    DARNASSUS("Classic", "Darnassus", "Alliance", 69),
    EXODAR("Classic", "Exodar", "Alliance", 930),
    GILNEAS("Classic", "Gilneas", "Alliance", 1134),
    GNOMEREGAN("Classic", "Gnomeregan", "Alliance", 54),
    IRONFORGE("Classic", "Ironforge", "Alliance", 47),
    STORMWIND("Classic", "Stormwind", "Alliance", 72),
    TUSHUI_PANDAREN("Classic", "Tushui Pandaren", "Alliance", 1353),
    BILGEWATER_CARTEL("Classic", "Bilgewater Cartel", "Horde", 1133),
    DARKSPEAR_TROLLS("Classic", "Darkspear Trolls", "Horde", 530),
    ORGRIMMAR("Classic", "Orgrimmar", "Horde", 76),
    SILVERMOON_CITY("Classic", "Silvermoon City", "Horde", 911),
    THUNDER_BLUFF("Classic", "Thunder Bluff", "Horde", 81),
    UNDERCITY("Classic", "Undercity", "Horde", 68),
    HUOJIN_PANDAREN("Classic", "Huojin Pandaren", "Horde", 1352),
    SILVERWING_SENTINELS("Classic", "Silverwing Sentinels", "Forces", 890),
    STORMPIKE_GUARD("Classic", "Stormpike Guard", "Forces", 730),
    THE_LEAGUE_OF_ARATHOR("Classic", "The League of Arathor", "Forces", 509),
    FROSTWOLF_CLAN("Classic", "Frostwolf Clan", "Forces", 729),
    THE_DEFILERS("Classic", "The Defilers", "Forces", 510),
    BRAWLGAR_ARENA_S1("Classic", "Brawl'gar Arena (Season 1)", "brawlgar", 1374),
    BRAWLGAR_ARENA_S2("Classic", "Brawl'gar Arena (Season 2)", "brawlgar", 1691),
    BRAWLGAR_ARENA_S3("Classic", "Brawl'gar Arena (Season 3)", "brawlgar", 2010),
    BRAWLGAR_ARENA_S4("Classic", "Brawl'gar Arena (Season 4)", "brawlgar", 2372),
    WARSONG_OUTRIDERS("Classic", "Warsong Outriders", "Forces", 889),
    RATCHET("Classic", "Ratchet", "Steamwheedle Cartel", 470),
    BOOTY_BAY("Classic", "Booty Bay", "Steamwheedle Cartel", 21),
    EVERLOOK("Classic", "Everlook", "Steamwheedle Cartel", 577),
    GADGETZAN("Classic", "Gadgetzan", "Steamwheedle Cartel", 369);

    var xpac: String = expansion
    var repName: String = name
    var factionName: String = faction
    var id: Int = id

    companion object {
        fun getFaction(value: String): String? = values().find { it.repName == value }?.factionName
    }
}