package com.BlizzardArmory.util.state

enum class FragmentTag {
    WOWFAVORITES, D3FAVORITES, OWFAVORITES, D3NAV, D3FRAGMENT, D4FRAGMENT, D3LEADERBOARD, WOWRAIDLEADERBOARD, WOWMPLUSLEADERBOARD,
    WOWPVPLEADERBOARD, WOWGUILDNAVFRAGMENT, NAVFRAGMENT, WOWFRAGMENT, WOWFRAGMENTCLASSIC, WOWFRAGMENTCLASSICERA, SC2FRAGMENT, OVERWATCHFRAGMENT, NEWSPAGEFRAGMENT,
    SETTINGSFRAGMENT, SC2LEADERBOARD, HELPFRAGMENT, LIBSFRAGMENT, OVERWATCHLEAGUE, AUTHORIZATIONFRAGMENT
}